### ISSUE TITLE
Segmentation fault (MinerCLI)

### ISSUE THREAD

**Issue by levongh** [energicryptocurrency/energiminer#3]
In doGBT function we are using `exit(0)`, it is usually a rather brutal and nondeterministic way to end a program even with a single thread. Here we are working with multiple threads` 
    1. The stack and heap objects of each thread will not be destroyed properly and we are getting memory leak.
    2. In Some cases this nondeterminism is causing to segmentation fault issue.

**Comment by levongh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Segmentation fault (MinerCLI)](https://trello.com/c/FbMEZJID/127-segmentation-fault-minercli)

**Comment by RyanLucchese** [comment]
Fixed by #8
