### ISSUE TITLE
Hashrate slows when using multiple cards.

### ISSUE THREAD

**Issue by RyanLucchese** [energicryptocurrency/energiminer#34]
Users have reported a slowing of hashrate when running multiple card rigs. One user reported total hashrate unable to exceed 70 MH/s - so hashrate per card diminishes at 3+ cards.

Most users reporting this issue seem to be running nvidia cards.

**Comment by levongh** [comment]
There are some additional instructions.

1. Try update drivers.
      download and install the latest.

2.Try update energiminer
      download latest release.

3. For CUDA devices use use -U flag which will enable the CUDA miner
  
4. Try to change P2 State and Power management mode
       You can use  [NVidiaProfileInspectorDmW](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW)
       For the best mining hashrate choose from sector "5 - Common":

      - CUDA - Force P2 State (Set to "Off")
      - Power managment mode (Set to "Prefer maximum performance")

5. Try Tweak Win10.
        You can use [Windows10MiningTweaksDmW](https://github.com/DeadManWalkingTO/Windows10MiningTweaksDmW) (Solution for 100% CPU usage (Win10 - CUDA - OpenCL))

6. Try Optimize/Overclock GPUs. 
    You can use [MSI Afterburner](https://www.msi.com/page/afterburner) for GPU OverClock/Optimize.

**Comment by andvgal** [comment]
Done, since v2.2 - command pipeline is under constant load now + do not use OpenCL for NVIDIA.
