### ISSUE TITLE
block height mismatch in coinbase

### ISSUE THREAD

**Issue by levongh** [energicryptocurrency/energiminer#4]
coinbase starts with serialized block height, but we send not complete coinbase data.

**Comment by levongh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [block height mismatch in coinbase](https://trello.com/c/mcHnSzOH/128-block-height-mismatch-in-coinbase)

**Comment by RyanLucchese** [comment]
Fixed by #6
