### ISSUE TITLE
API not provided or not properly documented

### ISSUE THREAD

**Issue by melt7777** [energicryptocurrency/energiminer#68]
Hello, I noticed you ripped out all the API commands.

`The following argument was not expected: --api-port`

Please restore the API so that we can monitor this miner via JSON output as we do with other production-worthy miners, such as ethminer, claymore, etc. 

API is required to monitor the miner's statistics. 

Thank you very much!

~ melt
getpimp.org | miner.farm

**Comment by andvgal** [comment]
There API has never been part of the Energi Core.

However, no more releases of `Energi Miner` are planned after `Energi Core v2.0`.

**Comment by melt7777** [comment]
This is bad news.

Having no API means professionals will not use this software. Please use proper application development conventions in future projects. Providing an API is conventional for this type of application. 

Thank you!
