### ISSUE TITLE
Energiminer does not recognize AMD GPUs

### ISSUE THREAD

**Issue by Charlie-Govin** [energicryptocurrency/energiminer#69]
Many people are experiencing problems with energiminer. Energiminer does not recognize AMD GPUs. Energiminer only detect my Intel onboard graphics card and do not detect my AMD GPU. The same thing is happening to more people, I read in forums

**Comment by andvgal** [comment]
That's usually a problem of not properly selecting `--opencl-platform` based on `--list-devices`.
However, no more released of `Energi Miner` are planned after `Energi Core v2.0`.
