### ISSUE TITLE
Optimization for RX550 and RX560 cards

### ISSUE THREAD

**Issue by caowenyu75** [energicryptocurrency/energiminer#70]
The hashrates are pretty bad for rx550 and 560 cards. Is it possible to do the optimization for the related GPUs?
Also, I noticed the miner stayed idle after some time, which could be fixed by hit enter. 

Thank you.

**Comment by andvgal** [comment]
Incorrect setup of local/global work parameters may lead to large fluctuation of hashrate or too high CPU usage what downgrades performance.

Minor fluctuation is normal due display of true absolute average hashrate, but not relative hashrate based on the last job done.

Some GPUs may have non-standard components or fake VBIOS. For example, some mining Vega56 cards are branded as Vega64. You can try to disable binary kernels with `-cl-only`.

In any case, no new miner releases are planned. So, the ticket is closed.
